version: "3.7"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    image: mysql:5.7.37-oracle
    environment:
      MYSQL_DATABASE: "cars"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./api/data:/var/lib/mysql
    user: mysql
    ports:
      - 3306:3306
